repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
    - id: golangci-lint
      name: golangci-lint
      description: Lint
      entry: golangci-lint run --fix
      types: [ go ]
      language: golang
      pass_filenames: false
